"""
Student information for this assignment:

Replace <SAISRIKAR KICHILI> with your name.
On my/our honor, <SAISRIKAR KICHILI> and <ANIKA KOPPULA>, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: srk2749
UT EID 2: ark3398
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    maximum = 0
    x = len(s)
    for i in range(x):
        z = [0] * 256
        length = 0
        for j in range(i, x):
            value = ord(s[j])
            z[value] += 1
            if z[value] > 1:
                break
            length += 1
            maximum = max(maximum, length)
    return maximum


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    maximum = 0
    x = len(s)
    for i in range(x):
        z = [0] * 256
        length = 0
        for j in range(i, x):
            value = ord(s[j])
            z[value] += 1
            if z[value] > 1:
                break
            length += 1
            maximum = max(maximum, length)
    return maximum


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    maximum = 0
    x = 0
    z = [0] * 256
    for i in range(len(s)):
        output = ord(s[i])
        z[output] += 1
        while z[output] > 1:
            z[ord(s[x])] -= 1
            x += 1
        maximum = max(maximum, i - x + 1)
    return maximum
